sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t jwatkins12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jwatkins12/docker-react npm run test