sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t jwatkins12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jwatkins12/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-615389170786"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master

    